# The `release` operation is never automatic; you must manually invoke the workflow explicitly
name: release
on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Which version number to bump (patch, minor, major, or specific version)'
        required: true

jobs:
  rust-release:
    uses: elastio/actions/.github/workflows/rust-release.yml@v1
    secrets: inherit
    with:
      bump_level: ${{ github.event.inputs.bump_level }}
